timeout: 30 # # 주문이 대기 중인 경우 최대 대기시간 (초)
r: 0.1 # 'A' 코인에 10 만큼 할당이 되었을 때, `R` 이 1.0 이라면 100% 사용하여 주문

# 몰빵이 아닌 분산 투자 전략을 위한 것
# 총 자금이 100, 'A' 코인에 최대 10 만큼의 자금 할당시 'A' => 0.1 (비중)
coins:
  XRP: 1.0 # 리플
  DOGE: 1.0 # 도지
  BTT: 1.0 # 비트토렌트
  TRX: 1.0 # 트론
  MED: 1.0 # 메디블록
  EOS: 1.0 # 이오스
  VET: 1.0 # 비체인
  ETC: 1.0 # 이더리움 클래식
  CHZ: 1.0 # 칠리즈
  QTUM: 1.0 # 퀀텀

