c: 0.2 # 코인이 가질 자금 대비 최대 보유비중 자금이 100일 떄 'A' 코인이 가질 수 있는 최대 비중은 10%
r: 0.5 # 'A' 코인에 10 만큼 할당이 되었을 때, `R` 이 1.0 이라면 100% 사용하여 주문

k: 0.5 # 변동성 돌파 상수

timeout: 30 # # 주문이 대기 중인 경우 최대 대기시간 (초)
max: 5 # 데이터베이스에서 관리 할 (트래킹 할) 코인의 갯수